baseURL = "https://bcyfo5u0v38t.github.io/"
theme = "LoveIt"
title = "bcyfo5u0v38t's Blog"
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true
[author]
name = "bcyfo5u0v38t"
email = "bcyfo5u0v38t@gmail.com"
link = "https://github.com/bcyfo5u0v38t"
[menu]
[[menu.main]]
weight = 1
identifier = "posts"
pre = ""
post = ""
name = "文章"
url = "/posts/"
title = ""
[[menu.main]]
weight = 2
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
[[menu.main]]
weight = 3
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""